'use strict';

const {
  REMOTE_CHOICES,
  EMPLOYMENT_TYPE_CHOICES,
  SENIORITY_CHOICES,
  CATEGORY_CHOICES,
} = require('./constants');

const filterFields = [
  {
    key: 'q',
    label: 'Keywords',
    type: 'string',
    required: false,
    helpText:
      'Full-text search over job title, company name and location (not the description), for example `data engineer`. Words are matched exactly: `engineer` does not match `engineering`.',
  },
  {
    key: 'country',
    label: 'Countries',
    type: 'string',
    list: true,
    required: false,
    helpText: 'Two-letter ISO country codes, for example `DE`, `GB` or `US`. Add one code per line.',
  },
  {
    key: 'remote',
    label: 'Work arrangement',
    type: 'string',
    list: true,
    required: false,
    choices: REMOTE_CHOICES,
    helpText: 'Only jobs with this remote status.',
  },
  {
    key: 'employment_type',
    label: 'Employment type',
    type: 'string',
    list: true,
    required: false,
    choices: EMPLOYMENT_TYPE_CHOICES,
    helpText: 'Only jobs with this employment type.',
  },
  {
    key: 'seniority',
    label: 'Seniority',
    type: 'string',
    list: true,
    required: false,
    choices: SENIORITY_CHOICES,
    helpText: 'Only jobs at this seniority level.',
  },
  {
    key: 'category',
    label: 'Category',
    type: 'string',
    list: true,
    required: false,
    choices: CATEGORY_CHOICES,
    helpText: 'Only jobs in this job family.',
  },
  {
    key: 'company',
    label: 'Companies',
    type: 'string',
    list: true,
    required: false,
    dynamic: 'company_list.slug.name',
    search: 'find_company.slug',
    helpText: 'Only jobs at these employers. Pick from the list or enter company slugs such as `google`.',
  },
];

const includeDescriptionField = {
  key: 'include_description',
  label: 'Include description',
  type: 'boolean',
  required: false,
  default: 'false',
  helpText: 'Also return the job advert text (plain text) in the `description` field.',
};

const jobOutputFields = [
  { key: 'id', label: 'Job ID' },
  { key: 'slug', label: 'Job slug' },
  { key: 'title', label: 'Title' },
  { key: 'company', label: 'Company' },
  { key: 'company_slug', label: 'Company slug' },
  { key: 'company_logo', label: 'Company logo URL' },
  { key: 'location', label: 'Location' },
  { key: 'city', label: 'City' },
  { key: 'region', label: 'Region (US state)' },
  { key: 'country', label: 'Country (ISO code)' },
  { key: 'remote', label: 'Work arrangement' },
  { key: 'employment_type', label: 'Employment type' },
  { key: 'seniority', label: 'Seniority' },
  { key: 'category', label: 'Category' },
  { key: 'posted_at', label: 'Posted at', type: 'datetime' },
  { key: 'first_seen_at', label: 'First seen at', type: 'datetime' },
  { key: 'last_verified_at', label: 'Last verified at', type: 'datetime' },
  { key: 'status', label: 'Status' },
  { key: 'closed_at', label: 'Closed at', type: 'datetime' },
  { key: 'closed_reason', label: 'Closed reason' },
  { key: 'apply_url', label: 'Apply URL (employer)' },
  { key: 'salary_min', label: 'Salary minimum', type: 'number' },
  { key: 'salary_max', label: 'Salary maximum', type: 'number' },
  { key: 'salary_currency', label: 'Salary currency' },
  { key: 'salary_period', label: 'Salary period' },
  { key: 'source', label: 'Source' },
  { key: 'source_type', label: 'Source type' },
  { key: 'description', label: 'Description (plain text)' },
  { key: 'attribution', label: 'Attribution (show with the listing when present)' },
  { key: 'canonical_url', label: 'Canonical URL (link here when present)' },
];

const jobSample = {
  id: 'defb93bc-0de5-432d-8323-185757ba256f',
  slug: 'warehouse-associate-defb93bc',
  title: 'Warehouse Associate',
  company: 'Example Logistics',
  company_slug: 'example-logistics',
  company_logo: 'https://jobopportunitiesapi.org/static/example-logo.png',
  location: 'Hamburg, Germany',
  city: 'Hamburg',
  country: 'DE',
  remote: 'on_site',
  remote_inferred: true,
  employment_type: 'Full-time',
  seniority: 'Entry',
  category: 'Logistics & Transport',
  posted_at: '2026-10-05T17:16:38Z',
  first_seen_at: '2026-10-05T15:29:41Z',
  last_verified_at: '2026-10-05T18:18:53Z',
  status: 'live',
  closed_at: null,
  closed_reason: null,
  apply_url: 'https://example-logistics.jobs.example/job/2828434',
  source: 'personio',
  source_type: 'ats',
  has_description: true,
  description_length: 3282,
  field_sources: {
    remote: 'inferred',
    location: 'published',
    posted_at: 'published',
    salary: 'absent',
  },
};

const companyOutputFields = [
  { key: 'slug', label: 'Company slug' },
  { key: 'name', label: 'Name' },
  { key: 'website', label: 'Website' },
  { key: 'logo', label: 'Logo URL' },
  { key: 'country', label: 'Country (ISO code)' },
  { key: 'industry', label: 'Industry' },
  { key: 'org_type', label: 'Organisation type' },
  { key: 'open_roles', label: 'Open roles available in the API', type: 'integer' },
  { key: 'first_seen', label: 'First seen', type: 'datetime' },
];

const companySample = {
  slug: 'example-logistics',
  name: 'Example Logistics',
  website: 'example-logistics.example',
  logo: 'https://jobopportunitiesapi.org/static/example-logo.png',
  country: 'DE',
  industry: 'Logistics',
  org_type: 'Enterprise',
  sectors: ['Logistics & Transport', 'Operations & Admin'],
  open_roles: 12,
  own_site_roles: 0,
  source_types: ['ats'],
  first_seen: '2026-07-14',
};

module.exports = {
  filterFields,
  includeDescriptionField,
  jobOutputFields,
  jobSample,
  companyOutputFields,
  companySample,
};
